### ISSUE TITLE
.bmp wont grab 

### ISSUE THREAD

**Issue by tonywarriner** [benbaker76/Gfx2Next#24]
.bmp file will only grab if 48x48 size. 48x16 or 48x32 fail with  - 

Invalid size of BMP file. 
The file Melon.bmp is not a valid of supported BMP file

(written by Aseprite)

Gfx2Next -sprites -tile-size=16x16 -colors-4bit -pal-ext -bank-8k Melon.bmp
[bmp_files.zip](https://github.com/user-attachments/files/16403946/bmp_files.zip)

**Comment by benbaker76** [comment]
This is the output I get using your files and the same command line arguments in Gfx2Next v1.1.17:
```
>Gfx2Next -sprites -tile-size=16x16 -colors-4bit -pal-ext -bank-8k Melon.bmp
Tile Size = 16 x 16
Bank Size = 8192
Processing 'Melon.bmp'...
Sprite Count = 6

>Gfx2Next -sprites -tile-size=16x16 -colors-4bit -pal-ext -bank-8k Melon2.bmp
Tile Size = 16 x 16
Bank Size = 8192
Processing 'Melon2.bmp'...
Sprite Count = 9
```
